import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-lg m-auto">
          <header className="flex flex-row justify-between">
            <div>Logo</div>
            <nav>
              <ul className="flex flex-row gap-4">
                <Link href="/">Home</Link>
                <Link href="/post">Post</Link>
              </ul>
            </nav>
          </header>
          <div>
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
